In [1]:
import pandas as pd

In [7]:
small_data = pd.read_csv('../data/raw/binding_site_small.csv')
data = pd.read_csv('../data/raw/binding_site_training_data.csv')

In [8]:
data

,SMILES,name,cat0,cat1,cat2,cat3
0,CC(=O)c(c1)c(=O)oc(c12)cccc2,3-Acetylcoumarin,0,1,0,0
1,O=C(O)C(C)c(c1C(=O)O)oc(c1C)CCC,3-Carboxy-4-methyl-5-propyl-2-furan-propionic ...,0,1,0,0
2,c1cccc(c12)OCCC2O,4-Chromanol,0,1,0,0
3,c1cccc(c12)oc(=O)cc2O,4-Hydroxycoumarin,0,1,0,0
4,O=C(O)Cc1cc(=O)oc(c12)cc(cc2)Nc3ccccc3,7-Anilinocoumarin-4-acetic acid,1,0,0,0
...,...,...,...,...,...,...
119,O=C(O)C(N)Cc1c[nH]c(c12)cccc2,Tryptophan,0,0,1,0
120,Cn1c(=O)n(C)c(=O)cc1NCCCN2CCN(CC2)c3c(OC)cccc3,Urapidil,0,1,0,0
121,COc(cc1)c(OC)cc1C(C#N)(C(C)C)CCCN(C)CCc2cc(OC)...,Verapamil,1,0,0,0
122,c1ccccc1C(CC(=O)C)c(c2O)c(=O)oc(c23)cccc3,Warfarin,0,1,0,0
123,O=C(O)Cc(n1C)cc(C)c1C(=O)c2ccc(Cl)cc2,Zomepirac,0,0,1,0

In [20]:
small_data.head()

,ligand,smiles,cat0,cat1,cat2,cat3,target
0,bicalutamide,CC(CS(=O)(=O)C1=CC=C(C=C1)F)(C(=O)NC2=CC(=C(...,1,0,0,0,0
1,idarubicine,CC1C(C(CC(O1)OC2CC(CC3=C2C(=C4C(=C3O)C(=O)C5...,1,0,0,0,0
2,teniposide,COC1=CC(=CC(=C1O)OC)C2C3C(COC3=O)C(C4=CC5=C(...,1,0,0,0,0
3,halothane,C(C(F)(F)F)(Cl)Br,0,0,1,0,2
4,propofol,CC(C)C1=C(C(=CC=C1)C(C)C)O,0,0,1,0,2

In [15]:
def generate_target(df, col_count=3):
    target = []
    interesting_columns = []
    for i in range(col_count):
        interesting_columns.append(df[f'cat{i}'])
    for args in zip(*interesting_columns):
        index = list(args).index(1)
        target.append(index)
    return pd.Series(target)

## Small data

In [16]:
small_target = generate_target(small_data, 4)

In [17]:
small_target.value_counts()

1    16
2    14
0    11
3     8
dtype: int64

In [18]:
small_data['target'] = small_target

In [21]:
small_data_filtered = pd.DataFrame({'smiles': small_data['smiles'], 'target': small_target})

In [23]:
small_data_filtered.to_csv('../data/preprocessed/small_site.csv', index=False)

## Big data

In [24]:
data = data[data.cat3 != 1]

In [25]:
data

,SMILES,name,cat0,cat1,cat2,cat3
0,CC(=O)c(c1)c(=O)oc(c12)cccc2,3-Acetylcoumarin,0,1,0,0
1,O=C(O)C(C)c(c1C(=O)O)oc(c1C)CCC,3-Carboxy-4-methyl-5-propyl-2-furan-propionic ...,0,1,0,0
2,c1cccc(c12)OCCC2O,4-Chromanol,0,1,0,0
3,c1cccc(c12)oc(=O)cc2O,4-Hydroxycoumarin,0,1,0,0
4,O=C(O)Cc1cc(=O)oc(c12)cc(cc2)Nc3ccccc3,7-Anilinocoumarin-4-acetic acid,1,0,0,0
...,...,...,...,...,...,...
119,O=C(O)C(N)Cc1c[nH]c(c12)cccc2,Tryptophan,0,0,1,0
120,Cn1c(=O)n(C)c(=O)cc1NCCCN2CCN(CC2)c3c(OC)cccc3,Urapidil,0,1,0,0
121,COc(cc1)c(OC)cc1C(C#N)(C(C)C)CCCN(C)CCc2cc(OC)...,Verapamil,1,0,0,0
122,c1ccccc1C(CC(=O)C)c(c2O)c(=O)oc(c23)cccc3,Warfarin,0,1,0,0
123,O=C(O)Cc(n1C)cc(C)c1C(=O)c2ccc(Cl)cc2,Zomepirac,0,0,1,0

In [26]:
target = generate_target(data, 3)

In [27]:
data_filtered = pd.DataFrame({'smiles': data['SMILES'], 'target': target})

In [28]:
data_filtered.to_csv('../data/preprocessed/site.csv', index=False)